import Head from "next/head";
import Image from "next/image";
import styles from "../styles/AboutUs.module.css";
import Navbar from "../components/headerSection/NavBarSub";
import AboutUs from "../components/aboutUsSection/AboutUS";
import Footer from "../components/footerSection/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Teambatography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.svg" />
      </Head>
      <Navbar />
      <AboutUs />
      <Footer />
    </div>
  );
}
