import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/headerSection/NavBar";
import Hero from "../components/heroSection/Hero";
import Service from "../components/serviceSection/Services";
import Footer from "../components/footerSection/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Teambatography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.svg" />
      </Head>
      <Navbar />
      <Hero />
      <Service />
      <Footer />
    </div>
  );
}
